//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAM {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setAccountDir {
            get {
                return ((string)(this["setAccountDir"]));
            }
            set {
                this["setAccountDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setIonCrossDir {
            get {
                return ((string)(this["setIonCrossDir"]));
            }
            set {
                this["setIonCrossDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWriteEncryptedFiles {
            get {
                return ((bool)(this["setWriteEncryptedFiles"]));
            }
            set {
                this["setWriteEncryptedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string setFLHookIP {
            get {
                return ((string)(this["setFLHookIP"]));
            }
            set {
                this["setFLHookIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1920")]
        public decimal setFLHookPort {
            get {
                return ((decimal)(this["setFLHookPort"]));
            }
            set {
                this["setFLHookPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test")]
        public string setFLHookPassword {
            get {
                return ((string)(this["setFLHookPassword"]));
            }
            set {
                this["setFLHookPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setFLDir {
            get {
                return ((string)(this["setFLDir"]));
            }
            set {
                this["setFLDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCheckChangedOnly {
            get {
                return ((bool)(this["setCheckChangedOnly"]));
            }
            set {
                this["setCheckChangedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setFLHookUnicode {
            get {
                return ((bool)(this["setFLHookUnicode"]));
            }
            set {
                this["setFLHookUnicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public decimal setDaysToDeleteInactiveChars {
            get {
                return ((decimal)(this["setDaysToDeleteInactiveChars"]));
            }
            set {
                this["setDaysToDeleteInactiveChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public decimal setSecsToDeleteUninterestedChars {
            get {
                return ((decimal)(this["setSecsToDeleteUninterestedChars"]));
            }
            set {
                this["setSecsToDeleteUninterestedChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setAutomaticCharWipe {
            get {
                return ((bool)(this["setAutomaticCharWipe"]));
            }
            set {
                this["setAutomaticCharWipe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setAutomaticCharClean {
            get {
                return ((bool)(this["setAutomaticCharClean"]));
            }
            set {
                this["setAutomaticCharClean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\web\\stats")]
        public string setStatisticsDir {
            get {
                return ((string)(this["setStatisticsDir"]));
            }
            set {
                this["setStatisticsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setStatsFactions {
            get {
                return ((string)(this["setStatsFactions"]));
            }
            set {
                this["setStatsFactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCheckDefaultEngine {
            get {
                return ((bool)(this["setCheckDefaultEngine"]));
            }
            set {
                this["setCheckDefaultEngine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCheckDefaultPowerPlant {
            get {
                return ((bool)(this["setCheckDefaultPowerPlant"]));
            }
            set {
                this["setCheckDefaultPowerPlant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setReportVisitErrors {
            get {
                return ((bool)(this["setReportVisitErrors"]));
            }
            set {
                this["setReportVisitErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setAutomaticFixErrors {
            get {
                return ((bool)(this["setAutomaticFixErrors"]));
            }
            set {
                this["setAutomaticFixErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setDebug {
            get {
                return ((decimal)(this["setDebug"]));
            }
            set {
                this["setDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setCheckDefaultLights {
            get {
                return ((bool)(this["setCheckDefaultLights"]));
            }
            set {
                this["setCheckDefaultLights"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMoveUninterestedChars {
            get {
                return ((bool)(this["setMoveUninterestedChars"]));
            }
            set {
                this["setMoveUninterestedChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setMoveUninterestedCharsDir {
            get {
                return ((string)(this["setMoveUninterestedCharsDir"]));
            }
            set {
                this["setMoveUninterestedCharsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public decimal setDaysInactiveToDeleteUninterestedChars {
            get {
                return ((decimal)(this["setDaysInactiveToDeleteUninterestedChars"]));
            }
            set {
                this["setDaysInactiveToDeleteUninterestedChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int setHistoryHorizon {
            get {
                return ((int)(this["setHistoryHorizon"]));
            }
            set {
                this["setHistoryHorizon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setShowQuitMsg {
            get {
                return ((bool)(this["setShowQuitMsg"]));
            }
            set {
                this["setShowQuitMsg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setShowUpdateDatabase {
            get {
                return ((int)(this["setShowUpdateDatabase"]));
            }
            set {
                this["setShowUpdateDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setShowMultibanSucc {
            get {
                return ((bool)(this["setShowMultibanSucc"]));
            }
            set {
                this["setShowMultibanSucc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setShowMultiunbanSucc {
            get {
                return ((bool)(this["setShowMultiunbanSucc"]));
            }
            set {
                this["setShowMultiunbanSucc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setShowMultideleteSucc {
            get {
                return ((bool)(this["setShowMultideleteSucc"]));
            }
            set {
                this["setShowMultideleteSucc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setFilterWaitForEnter {
            get {
                return ((bool)(this["setFilterWaitForEnter"]));
            }
            set {
                this["setFilterWaitForEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Character;System")]
        public string setStatPlayerListShowFields {
            get {
                return ((string)(this["setStatPlayerListShowFields"]));
            }
            set {
                this["setStatPlayerListShowFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ID;IP;Ping;Loss;Lag;Fluct;Saturation;TxQueue")]
        public string setStatPlayerListDontShowFields {
            get {
                return ((string)(this["setStatPlayerListDontShowFields"]));
            }
            set {
                this["setStatPlayerListDontShowFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2147483647")]
        public int setProcessorAffinity {
            get {
                return ((int)(this["setProcessorAffinity"]));
            }
            set {
                this["setProcessorAffinity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string setLoginIDBanFile {
            get {
                return ((string)(this["setLoginIDBanFile"]));
            }
            set {
                this["setLoginIDBanFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDisplayBannedCharsRed {
            get {
                return ((bool)(this["setDisplayBannedCharsRed"]));
            }
            set {
                this["setDisplayBannedCharsRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setStatPlayerListShowCharsBySys {
            get {
                return ((bool)(this["setStatPlayerListShowCharsBySys"]));
            }
            set {
                this["setStatPlayerListShowCharsBySys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setStatPlayerListShowCharsByName {
            get {
                return ((bool)(this["setStatPlayerListShowCharsByName"]));
            }
            set {
                this["setStatPlayerListShowCharsByName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setStatPlayerListTimeUTC {
            get {
                return ((bool)(this["setStatPlayerListTimeUTC"]));
            }
            set {
                this["setStatPlayerListTimeUTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setLoginIDs {
            get {
                return ((string)(this["setLoginIDs"]));
            }
            set {
                this["setLoginIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int setPlayerListUpdateInterval {
            get {
                return ((int)(this["setPlayerListUpdateInterval"]));
            }
            set {
                this["setPlayerListUpdateInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataJSON {
            get {
                return ((bool)(this["setDataJSON"]));
            }
            set {
                this["setDataJSON"] = value;
            }
        }
    }
}
